language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - composer install

after_script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
