language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - composer install
